### ISSUE TITLE
Download input files [glorys and ERA5]

### ISSUE THREAD

**Issue by nilodna** [lhico/pyroms_tools#33]
I'm thinking of creating two new scripts to help the user to download the initial/boundary conditions files (glorys) and meteorological forcing files (ERA5).

I just don't know if it's best to add new keys in the ```grid_config_pyroms.txt``` or just create a new config file mapping all the metadata we need to perform the download.

Right now, the [motu_wrappy](https://github.com/dksasaki/motu_wrappy) makes use of a ```motu_info.txt``` file and I believe we can merge this info inside the ```grid_config_pyroms.txt``` to converge all config information into one place. On the other hand, I'm afraid of a big and messy configuration file and I just don't know which option is better.

@dksasaki what do you think?

**Comment by dksasaki** [comment]
It sounds it will get big and messy.

Both packages have different objectives and baking them together could be a little troublesome in the future.

Maybe we can improve `motu_wrappy` and include an option to create a .json file with information that could be copied/imported into `pyroms_tools`. Or perhaps preparing configuring `motu_wrappy` as a real python module, that could be imported (optionally) into pyroms_tools?

**Comment by nilodna** [comment]
I definitely like the idea of configuring ```motu_wrappy``` to an installable package. Let's move this issue to https://github.com/dksasaki/motu_wrappy?

**Comment by dksasaki** [comment]
yeah, I think that would be better
