### ISSUE TITLE
including surface forcing scripts

### ISSUE THREAD

**Issue by dksasaki** [lhico/pyroms_tools#9]
Including modifications that will be used to generate the surface forcing files for roms. For now I'm prototyping it with era5 forcing files.

**Comment by dksasaki** [comment]
I updated the configs/grid_config_pyroms.txt to include information from era5. `scripts/era2roms.py` is the file that uses it. pyroms is not used in these scripts. We are just transforming the coordinates and names to the appropriate roms format (roms takes care of the interpolation).

**Comment by nilodna** [comment]
@dksasaki, you mentioned that you would like to refactor the module before merging it into the main branch. Could you list, if at hand, the refactoring points? I can refactor the module, since I'm starting to generate forcing files for my experiments.

**Comment by dksasaki** [comment]
Hey man, I actually ended up merging the branch related to this feature. Sorry about it - I forgot completely about the present issue. I did because there were people already working with the branch with atmos forcing and my update on the 2d interpolation was relevant in this case.

This choice  did not affect any script other than the ones relate to era5. Sorry about it again :sweat_smile:

**Comment by nilodna** [comment]
The script I developed to generate these forcing files is now tested and with great improvements to fill the gaps nearshore produced by the different land masks between ECMWF and the regional domain. 

I'm in the final stage of adaptation to the pyroms_tools structure and will update this soon.
